{
 "title": "Envoy Kafka protocol filter",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "brokerId",
    "query": "label_values(envoy_kafka_exampleprefix_request_produce_request,  brokerId)"
   }
  ]
 },
 "panels": [
  {
   "title": "Request rate 1min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_kafka_exampleprefix_request_produce_request[1m])",
     "legendFormat": "request broker-{{brokerId}}"
    },
    {
     "expr": "rate(envoy_kafka_exampleprefix_req[1m])",
     "legendFormat": "failure broker-{{brokerId}}"
    }
   ]
  },
  {
   "title": "Response rate 1min",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_kafka_exampleprefix_response_produce_response[1m])",
     "legendFormat": "response broker-{{brokerId}}"
    }
   ]
  },
  {
   "title": "Produce request 50% percentiles in 1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(envoy_kafka_exampleprefix_response_produce_response_duration_bucket{brokerId=\"$brokerId\"}[1m]))",
     "legendFormat": "broker-{{brokerId}}"
    }
   ]
  },
  {
   "title": "Produce request average response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_kafka_exampleprefix_response_produce_response_duration_sum{brokerId=\"$brokerId\"}/envoy_kafka_exampleprefix_response_produce_response_duration_count{brokerId=\"$brokerId\"}",
     "legendFormat": "broker-{{brokerId}}"
    }
   ]
  },
  {
   "title": "Fetch request 50% percentiles in 1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(envoy_kafka_exampleprefix_response_fetch_response_duration_bucket{brokerId=\"$brokerId\"}[1m]))",
     "legendFormat": "broker-{{brokerId}}"
    }
   ]
  },
  {
   "title": "Fetch request average response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_kafka_exampleprefix_response_fetch_response_duration_sum{brokerId=\"$brokerId\"}/envoy_kafka_exampleprefix_response_fetch_response_duration_count{brokerId=\"$brokerId\"}",
     "legendFormat": "broker-{{brokerId}}"
    }
   ]
  },
  {
   "title": "Metadata request 50% percentile in 1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(envoy_kafka_exampleprefix_response_metadata_response_duration_bucket{brokerId=\"$brokerId\"}[1m]))",
     "legendFormat": "broker-{{brokerId}}"
    }
   ]
  },
  {
   "title": "Metadata request average response time",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "envoy_kafka_exampleprefix_response_metadata_response_duration_sum{brokerId=\"$brokerId\"}/envoy_kafka_exampleprefix_response_metadata_response_duration_count{brokerId=\"$brokerId\"}",
     "legendFormat": "broker-{{brokerId}}"
    }
   ]
  },
  {
   "title": "Failure rate 1min",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(envoy_kafka_exampleprefix_req[1m])",
     "legendFormat": "failure broker-{{brokerId}"
    }
   ]
  }
 ]
}