{{ if .Values.bookings }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bookings-v1
  namespace: {{ .Release.Namespace }}
  labels:
    app: bookings
    version: v1
    {{ include "backyards-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: bookings
      version: v1
  template:
    metadata:
      labels:
        app: bookings
        version: v1
    spec:
      containers:
      - name: bookings
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        - containerPort: 8082
        - containerPort: 8083
        env:
        - name: WORKLOAD
          value: Echo
        - name: ECHO_STR
          value: "bookings service response"
        - name: REQUESTS
          value: "http://analytics:8080/#1 http://payments:8080/#1"
        {{- with .Values.resources }}
        resources:
          {{ toYaml . | nindent 12 }}
        {{- end }}
{{ end }}
