{{ if .Values.payments }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-v1
  namespace: {{ .Release.Namespace }}
  labels:
    app: payments
    version: v1
    {{ include "backyards-demo.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: payments
      version: v1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: payments
        version: v1
    spec:
      containers:
      - name: payments
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        - containerPort: 8082
        - containerPort: 8083
        env:
        - name: WORKLOAD
          value: Echo
        - name: ECHO_STR
          value: "payment received"
        - name: REQUESTS
          value: "http://notifications:8080#1"
        {{- with .Values.resources }}
        resources:
          {{ toYaml . | nindent 12 }}
        {{- end }}
{{ end }}
