apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "turbonomic-importer.fullname" . }}
  labels:
{{ include "turbonomic-importer.labels" . | indent 4 }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "turbonomic-importer.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "turbonomic-importer.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.1
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
        - args:
            - --metrics-addr=127.0.0.1:8080
            - --enable-leader-election
          command:
            - /app
          env:
            - name: TURBONOMIC_HOSTNAME
              value: {{ .Values.turbonomic.hostname }}
            - name: TURBONOMIC_USERNAME
              value: {{ .Values.turbonomic.username }}
            - name: TURBONOMIC_PASSWORD
              value: {{ .Values.turbonomic.password }}
            - name: TURBONOMIC_INSECURE_SKIP_VERIFY
              value: "{{ .Values.turbonomic.insecureSkipVerify }}"
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          name: manager
          resources:
{{ toYaml .Values.resources | nindent 12 }}
{{- with .Values.nodeSelector }}
      nodeSelector:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.affinity }}
      affinity:
{{- toYaml . | nindent 8 }}
{{- end }}
{{- with .Values.tolerations }}
      tolerations:
{{- toYaml . | nindent 8 }}
{{- end }}
      terminationGracePeriodSeconds: 10
