apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "backyards.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "backyards.name" . }}
    app.kubernetes.io/name: {{ include "backyards.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "backyards.fullname" . }}
  labels:
    app: {{ include "backyards.name" . }}
    app.kubernetes.io/name: {{ include "backyards.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
rules:
- apiGroups: [""]
  resources:
  - configmaps
  - endpoints
  - namespaces
  - services
  - pods
  - secrets
  - nodes
  - events
  verbs:
  - get
  - list
  - watch
- apiGroups: [""]
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
  - create
  - edit
  - update
  - patch
  - delete
- apiGroups: ["apps"]
  resources:
  - deployments
  - replicasets
  - statefulsets
  - daemonsets
  verbs:
  - get
  - list
  - watch
- apiGroups: ["batch"]
  resources:
  - jobs
  - cronjobs
  verbs:
  - get
  - list
  - watch
- apiGroups: ["istio.banzaicloud.io"]
  resources:
  - istios
  - remoteistios
  verbs:
  - create
  - delete
  - get
  - list
  - watch
  - edit
  - update
  - patch
- apiGroups: ["networking.istio.io"]
  resources:
  - destinationrules
  - virtualservices
  - gateways
  - serviceentries
  - sidecars
  verbs:
  - get
  - list
  - watch
  - create
  - edit
  - update
  - patch
  - delete
- apiGroups:
  - authentication.istio.io
  resources:
  - meshpolicies
  - policies
  verbs:
  - get
  - list
  - watch
  - create
  - edit
  - update
  - patch
  - delete
- apiGroups: ["deployments.banzaicloud.io"]
  resources:
  - canaries
  verbs:
  - get
  - list
  - watch
  - create
  - edit
  - update
  - patch
  - delete
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  - localsubjectaccessreviews
  verbs:
  - get
  - list
  - watch
  - create
- apiGroups:
  - extensions.banzaicloud.io
  resources:
  - metadata
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "backyards.fullname" . }}
  labels:
    app: {{ include "backyards.name" . }}
    app.kubernetes.io/name: {{ include "backyards.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: application
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
roleRef:
  kind: ClusterRole
  name: {{ include "backyards.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: {{ include "backyards.fullname" . }}
  namespace: {{ .Release.Namespace }}
