{{- if and .Values.application.enabled .Values.ingressgateway.meshgateway.enabled -}}
apiVersion: istio.banzaicloud.io/v1beta1
kind: MeshGateway
metadata:
  name: {{ include "ingressgateway.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "ingressgateway.name" . }}
    app.kubernetes.io/name: {{ include "ingressgateway.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: ingressgateway
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
spec:
  labels:
    app: {{ include "ingressgateway.name" . }}
    app.kubernetes.io/name: {{ include "ingressgateway.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: ingressgateway
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
  maxReplicas: 1
  minReplicas: 1
  ports:
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 80
  replicaCount: 1
  serviceType: {{ .Values.ingressgateway.service.type }}
  type: ingress
{{- end }}
