{{- if .Values.grafana.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "grafana.fullname" . }}-ds-0
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "grafana.name" . }}
    app.kubernetes.io/name: {{ include "grafana.name" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: grafana
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    grafana_datasource: "1"
data:
  datasources-0.yaml: |-
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      orgId: 1
      url: http://{{ include "prometheus.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.prometheus.service.port }}/prometheus
      access: proxy
      isDefault: true
      jsonData:
        timeInterval: 5s
      editable: true
{{- end }}
