{{ if and .Values.prometheus.enabled .Values.kubestatemetrics.enabled }}
kind: ServiceAccount
apiVersion: v1
metadata:
  name: {{ include "kubestatemetrics.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "kubestatemetrics.fullname" . }}
    app.kubernetes.io/name: {{ include "kubestatemetrics.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: kube-state-metrics
    app.kubernetes.io/part-of: {{ include "kubestatemetrics.name" . }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubestatemetrics.fullname" . }}
  labels:
    app: {{ include "kubestatemetrics.fullname" . }}
    app.kubernetes.io/name: {{ include "kubestatemetrics.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: kube-state-metrics
    app.kubernetes.io/part-of: {{ include "kubestatemetrics.name" . }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - nodes
  - pods
  - services
  - resourcequotas
  - replicationcontrollers
  - limitranges
  - persistentvolumeclaims
  - persistentvolumes
  - namespaces
  - endpoints
  verbs:
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - daemonsets
  - deployments
  - replicasets
  - ingresses
  verbs:
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  - daemonsets
  - deployments
  - replicasets
  verbs:
  - list
  - watch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - list
  - watch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
  - watch
- apiGroups:
  - authentication.k8s.io
  resources:
  - tokenreviews
  verbs:
  - create
- apiGroups:
  - authorization.k8s.io
  resources:
  - subjectaccessreviews
  verbs:
  - create
- apiGroups:
  - policy
  resources:
  - poddisruptionbudgets
  verbs:
  - list
  - watch
- apiGroups:
  - certificates.k8s.io
  resources:
  - certificatesigningrequests
  verbs:
  - list
  - watch
- apiGroups:
  - storage.k8s.io
  resources:
  - storageclasses
  - volumeattachments
  verbs:
  - list
  - watch
- apiGroups:
  - admissionregistration.k8s.io
  resources:
  - mutatingwebhookconfigurations
  - validatingwebhookconfigurations
  verbs:
  - list
  - watch
- apiGroups:
  - networking.k8s.io
  resources:
  - networkpolicies
  verbs:
  - list
  - watch
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "kubestatemetrics.fullname" . }}
  labels:
    app: {{ include "kubestatemetrics.fullname" . }}
    app.kubernetes.io/name: {{ include "kubestatemetrics.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: kube-state-metrics
    app.kubernetes.io/part-of: {{ include "kubestatemetrics.name" . }}
roleRef:
  name: {{ include "kubestatemetrics.fullname" . }}
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: {{ include "kubestatemetrics.fullname" . }}
  kind: ServiceAccount
  namespace: {{ .Release.Namespace }}
{{ end }}
