apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: "true"
  labels:
    app: {{ include "kubeletdiscovery.name" . }}
    app.kubernetes.io/name: {{ include "kubeletdiscovery.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: kubelet-discovery
    app.kubernetes.io/part-of: {{ include "kubeletdiscovery.name" . }}
    k8s-app: {{ include "kubeletdiscovery.name" . }}
    job-name: kubelet
  name: {{ include "kubeletdiscovery.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 10255
    protocol: TCP
  - name: cadvisor
    port: 4194
    protocol: TCP
  - name: https-metrics
    port: 10250
    protocol: TCP
  selector:
    app.kubernetes.io/name: {{ include "kubeletdiscovery.fullname" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  type: ClusterIP
