{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "backyards.name" . }}
    app.kubernetes.io/name: {{ include "backyards.name" . }}
    helm.sh/chart: {{ include "backyards.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | replace "+" "_" }}
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/part-of: {{ include "backyards.name" . }}
data:
  prometheus.yml: |
    global:
      scrape_interval: {{ .Values.prometheus.config.global.scrapeInterval }}
      scrape_timeout: {{ .Values.prometheus.config.global.scrapeTimeout }}
      evaluation_interval: {{ .Values.prometheus.config.global.evaluationInterval }}
    rule_files:
    - /etc/prometheus/rules/*.yaml
    scrape_configs:
    - job_name: prometheus
      metrics_path: {{ .Values.prometheus.externalUrl }}/metrics
      static_configs:
      - targets:
        - localhost:9090
    - job_name: istio-mesh
      scrape_interval: 1s
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - {{ .Values.istio.namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        regex: istio-telemetry;prometheus
        action: keep
    - job_name: istio-policy
      scrape_interval: 1s
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - {{ .Values.istio.namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        regex: istio-policy;http-monitoring
        action: keep
    - job_name: istio-telemetry
      scrape_interval: 1s
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - {{ .Values.istio.namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        regex: istio-telemetry;http-monitoring
        action: keep
    - job_name: pilot
      scrape_interval: 1s
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - {{ .Values.istio.namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        regex: istio-pilot;http-monitoring
        action: keep
    - job_name: galley
      scrape_interval: 1s
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - {{ .Values.istio.namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        regex: istio-galley;http-monitoring
        action: keep
    - job_name: envoy-stats
      scrape_interval: 1s
      metrics_path: /stats/prometheus
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_port_name]
        regex: .*-envoy-prom
        action: keep
      - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
        regex: ([^:]+)(?::\d+)?;(\d+)
        target_label: __address__
        replacement: $1:15090
        action: replace
      - regex: __meta_kubernetes_pod_label_(.+)
        action: labelmap
      - source_labels: [__meta_kubernetes_namespace]
        target_label: namespace
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        target_label: pod_name
        action: replace
      metric_relabel_configs:
      - source_labels: [cluster_name]
        regex: (outbound|inbound|prometheus_stats).*
        action: drop
      - source_labels: [tcp_prefix]
        regex: (outbound|inbound|prometheus_stats).*
        action: drop
      - source_labels: [listener_address]
        regex: (.+)
        action: drop
      - source_labels: [http_conn_manager_listener_prefix]
        regex: (.+)
        action: drop
      - source_labels: [http_conn_manager_prefix]
        regex: (.+)
        action: drop
      - source_labels: [__name__]
        regex: envoy_tls.*
        action: drop
      - source_labels: [__name__]
        regex: envoy_tcp_downstream.*
        action: drop
      - source_labels: [__name__]
        regex: envoy_http_(stats|admin).*
        action: drop
      - source_labels: [__name__]
        regex: envoy_cluster_(lb|retry|bind|internal|max|original).*
        action: drop
    - job_name: kube-state-metrics
      scrape_interval: 1s
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - {{ .Release.Namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        regex: {{ include "kubestatemetrics.fullname" . }};http-monitoring
        action: keep
    - job_name: kubelet
      scrape_interval: 30s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: https
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - {{ .Release.Namespace }}
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_component]
        separator: ;
        regex: kubelet-discovery
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_instance]
        separator: ;
        regex: {{ .Release.Name }}
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        separator: ;
        regex: https-metrics
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_node_name]
        separator: ;
        regex: (.*)
        target_label: node
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: service
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_label_job_name]
        separator: ;
        regex: (.+)
        target_label: job
        replacement: ${1}
        action: replace
      - separator: ;
        regex: (.*)
        target_label: endpoint
        replacement: https-metrics
        action: replace
      - source_labels: [__metrics_path__]
        separator: ;
        regex: (.*)
        target_label: metrics_path
        replacement: $1
        action: replace
    - job_name: kubelet-cadvisor
      scrape_interval: 30s
      scrape_timeout: 10s
      metrics_path: /metrics/cadvisor
      scheme: https
      kubernetes_sd_configs:
        - role: endpoints
          namespaces:
            names:
            - {{ .Release.Namespace }}
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        insecure_skip_verify: true
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_component]
        separator: ;
        regex: kubelet-discovery
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_service_label_app_kubernetes_io_instance]
        separator: ;
        regex: {{ .Release.Name }}
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        separator: ;
        regex: https-metrics
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_node_name]
        separator: ;
        regex: (.*)
        target_label: node
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: service
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_label_job_name]
        separator: ;
        regex: (.+)
        target_label: job
        replacement: ${1}
        action: replace
      - separator: ;
        regex: (.*)
        target_label: endpoint
        replacement: https-metrics
        action: replace
      - source_labels: [__metrics_path__]
        separator: ;
        regex: (.*)
        target_label: metrics_path
        replacement: $1
        action: replace
    - job_name: node-exporter
      honor_timestamps: true
      scrape_interval: 30s
      scrape_timeout: 10s
      metrics_path: /metrics
      scheme: http
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - {{ .Release.Namespace }}
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_app]
        separator: ;
        regex: prometheus-node-exporter
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_port_name]
        separator: ;
        regex: metrics
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
        separator: ;
        regex: Node;(.*)
        target_label: node
        replacement: ${1}
        action: replace
      - source_labels: [__meta_kubernetes_endpoint_address_target_kind, __meta_kubernetes_endpoint_address_target_name]
        separator: ;
        regex: Pod;(.*)
        target_label: pod
        replacement: ${1}
        action: replace
      - source_labels: [__meta_kubernetes_namespace]
        separator: ;
        regex: (.*)
        target_label: namespace
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_name]
        separator: ;
        regex: (.*)
        target_label: service
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_pod_name]
        separator: ;
        regex: (.*)
        target_label: pod
        replacement: $1
        action: replace
      - source_labels: [__meta_kubernetes_service_label_job_name]
        separator: ;
        regex: (.+)
        target_label: job
        replacement: ${1}
        action: replace
      - separator: ;
        regex: (.*)
        target_label: endpoint
        replacement: metrics
        action: replace
      - source_labels: [__metrics_path__]
        separator: ;
        regex: (.*)
        target_label: metrics_path
        replacement: $1
        action: replace
    - job_name: 'federate'
      scrape_interval: 15s
      honor_labels: true
      metrics_path: '/prometheus/federate'
      kubernetes_sd_configs:
      - role: service
        namespaces:
          names:
          - backyards-system
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_backyards_banzaicloud_io_federated_prometheus]
        separator: ;
        regex: 'true'
        replacement: $1
        action: keep
      - source_labels: [__meta_kubernetes_service_label_backyards_banzaicloud_io_cluster_name]
        separator: ;
        regex: (.*)
        target_label: clustername
        replacement: $1
        action: replace
      params:
        'match[]':
          - '{job="envoy-stats"}'
          - '{job="kubelet"}'
          - '{job="kubelet-cadvisor"}'
          - '{job="kube-state-metrics"}'
          - '{job="node-exporter"}'
{{- end }}
