apiVersion: v1
appVersion: 0.1.6
description: Turbonomic importer for backyards
home: https://banzaicloud.com
icon: https://banzaicloud.com/img/banzai-cloud-logo.png
maintainers:
- email: info@banzaicloud.com
  name: Banzai Cloud
name: turbonomic-importer
version: 0.1.7
