#!/bin/bash
DOCS_DIR=${1:-$PWD/.docs-diff}
ORIG_DOCS_DIR=${2:-$PWD/cmd/docs}
GENERATE_GO_PATH=${2:-$PWD/cmd/docs/generate.go}
DIR=$(dirname $0)

mkdir -p $DOCS_DIR
retVal=$?
if [ $retVal -ne 0 ]; then
    exit $retVal
fi

cp $GENERATE_GO_PATH $DOCS_DIR && cd $DOCS_DIR && go run -v generate.go
retVal=$?
if [ $retVal -ne 0 ]; then
    exit $retVal
fi

diff -urN -I '^###### Auto generated by spf13/cobra' $DOCS_DIR $ORIG_DOCS_DIR
retVal=$?
if [ $retVal -ne 0 ]; then
    rm -rf DOCS_DIR
    exit $retVal
fi

echo "no difference for docs - ok!"

rm -rf $DOCS_DIR
