# Default values for backyards-demo.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 2

image:
  repository: banzaicloud/allspark
  tag: "0.1.2"
  pullPolicy: IfNotPresent

resources:
  limits:
   cpu: 1500m
   memory: 256Mi
  requests:
   cpu: 250m
   memory: 64Mi

services: true

istioresources: true

bombardier: true
analytics: true
bookings: true
catalog: true
frontpage: true
moviesv1: true
moviesv2: true
moviesv3: true
notifications: true
payments: true
database: true
